using System.Security.Cryptography;
using System.Text;

namespace Bullish.Signer;

/// <summary>
/// Used to sign API requests to the Bullish exchange
/// </summary>
public static class RequestSigner
{
    /// <summary>
    /// Sign an API request for the Bullish exchange
    /// </summary>
    /// <param name="eosWifPrivateKey">API private key with format "PUB_R1_6zN...kYk"</param>
    /// <param name="eosWifPublicKey">API public key with format "PVT_R1_6zN...kYk"</param>
    /// <param name="jsonPayload">The JSON payload to be signed</param>
    /// <returns>A signature with format "SIG_R1_Kac...9jx"</returns>
    public static string Sign(string eosWifPrivateKey, string eosWifPublicKey, string jsonPayload)
    {
        var digest = SHA256.HashData(Encoding.UTF8.GetBytes(jsonPayload));

        var privateKey = RequestSignerImpl.GetEosPrivateKey(eosWifPrivateKey);
        var publicKey = RequestSignerImpl.GetEosPublicKey(eosWifPublicKey);

        return RequestSignerImpl.SignRequest(digest, privateKey, publicKey);
    }

    /// <summary>
    /// Sign an API request for the Bullish exchange
    /// </summary>
    /// <param name="publicKey">The EOS private key</param>
    /// <param name="privateKey">The EOS public key</param>
    /// <param name="jsonPayload">The JSON payload to be signed</param>
    /// <returns>A signature with format "SIG_R1_Kac...9jx"</returns>
    public static string Sign(EosPrivateKey privateKey, EosPublicKey publicKey, string jsonPayload)
    {
        var digest = SHA256.HashData(Encoding.UTF8.GetBytes(jsonPayload));

        return RequestSignerImpl.SignRequest(digest, privateKey, publicKey);
    }

    /// <summary>
    /// Verify a signature generated by <see cref="Sign"/>
    /// </summary>
    /// <param name="signature">The signature generated by <see cref="Sign"/></param>
    /// <param name="eosWifPublicKey">API public key with format "PVT_R1_6zN...kYk"</param>
    /// <param name="jsonPayload">The JSON payload that was signed</param>
    public static bool Verify(string signature, string eosWifPublicKey, string jsonPayload)
    {
        var digest = SHA256.HashData(Encoding.UTF8.GetBytes(jsonPayload));

        var publicKey = RequestSignerImpl.GetEosPublicKey(eosWifPublicKey);
        return RequestSignerImpl.VerifySignature(digest, signature, publicKey);
    }

    /// <summary>
    /// Gets a structured EOS private key from an EOS WIF formatted private key
    /// </summary>
    /// <param name="eosWifPrivateKey">API private key with format "PUB_R1_6zN...kYk"</param>
    public static EosPrivateKey GetEosPrivateKey(string eosWifPrivateKey) =>
        RequestSignerImpl.GetEosPrivateKey(eosWifPrivateKey);

    /// <summary>
    /// Gets a structured EOS public key from an EOS WIF formatted public key
    /// </summary>
    /// <param name="eosWifPublicKey">API public key with format "PVT_R1_6zN...kYk"</param>
    public static EosPublicKey GetEosPublicKey(string eosWifPublicKey) =>
        RequestSignerImpl.GetEosPublicKey(eosWifPublicKey);
}